### ISSUE TITLE
Can't install on Atom 1.0.7

### ISSUE THREAD

**Issue by shawninder** [balupton/atom-semicolons#10]
``` bash
$ apm install atom-semicolons
Installing atom-semicolons to /Users/shawn/.atom/packages ✗
No available version compatible with the installed Atom version: 1.0.7
```

**Comment by balupton** [comment]
due to:
- https://github.com/balupton/atom-semicolons/issues/8
- https://github.com/balupton/atom-semicolons/issues/7
- https://github.com/balupton/atom-semicolons/issues/6

happy for pull request, as well as other maintainers

**Comment by balupton** [comment]
https://github.com/balupton/atom-semicolons/issues/12
